export const GET_POPULAR_MOVIES_SUCCESS = "GET_POPULAR_MOVIES_SUCCESS";
export const GET_POPULAR_MOVIES_LOADING = "GET_POPULAR_MOVIES_LOADING";
export const GET_POPULAR_MOVIES_ERROR = "GET_POPULAR_MOVIES_ERROR";

export const GET_RELATED_MOVIES_SUCCESS = "GET_RELATED_MOVIES_SUCCESS";
export const GET_RELATED_MOVIES_LOADING = "GET_RELATED_MOVIES_LOADING";
export const GET_RELATED_MOVIES_ERROR = "GET_RELATED_MOVIES_ERROR";
